# Generated by Django 4.2.9 on 2024-01-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SoftwareDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descriptions", models.CharField(max_length=255)),
                ("yearly_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("purchase_date", models.DateField()),
                ("support_end", models.DateField(blank=True, null=True)),
                ("renewal_date", models.DateField()),
                ("remark", models.CharField(max_length=255)),
                ("email_address", models.EmailField(max_length=254)),
                ("vendor_name", models.CharField(max_length=255)),
            ],
        ),
    ]
