# Generated by Django 4.2.9 on 2024-01-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celery_app", "0002_alter_softwaredetails_support_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="softwaredetails",
            name="remark",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
